# Copyright (c) 2019, WSO2 Inc. (http://wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# TestGrid Test Configuration Parameters
version: '0.9'
emailToList: "riyafa@wso2.com,builder@wso2.org"
infrastructureConfig:
  infrastructureProvider: SHELL
  containerOrchestrationEngine: K8S
  includes:
    - Ubuntu-18.04
    - OracleJDK-8
  provisioners:
  - name: ballerina-deployment
    remoteRepository: "https://github.com/ballerina-platform/ballerina-scenario-tests.git"
    remoteBranch: "master"
    description: creates infrastructure for ballerina scenario tests
    scripts:
      - name: ballerina-deployment
        description: Creates Kubernetes infrastructure for a ballerina installed instance.
        type: SHELL
        phase: CREATE
        file: test-grid-scripts/common/common_infra.sh
      - name: destroy
        file: test-grid-scripts/common/common_cleanup.sh
        type: SHELL
        phase: DESTROY
deploymentConfig:
  deploymentPatterns:
    - name: 'dual-channel-with-artemis-connector'
      description: 'artemis-scenario-tests'
      remoteRepository: "https://github.com/ballerina-platform/ballerina-scenario-tests.git"
      remoteBranch: "master"
      dir: .
      scripts:
        - name: 'default'
          type: SHELL
          file: test-grid-scripts/connectors/artemis/deployment-artemis-connector.sh
          inputParameters:
            BallerinaVersionType: "LatestSnapshot"
            isDebugEnabled: "true"
            TestGroup: "ArtemisConnector"
scenarioConfigs:
- testType: TESTNG
  remoteRepository: "https://github.com/ballerina-platform/ballerina-scenario-tests.git"
  remoteBranch: "master"
  name: "ballerinaScenarios"
  description: "artemis-scenario-tests"
  file: test-grid-scripts/connectors/artemis/artemis-test-runner.sh
  inputParameters:
    isDebugEnabled: "true"
